# vim:ft=dosini
[base]
default          = #ffffff
unknown-token    = #fa999c,bold
commandseparator = #7ae1d8
redirection      = #7ae1d8
here-string-tri  = #d3d8de
here-string-text = #d3d8de
here-string-var  = #d3d8de
exec-descriptor  = none
comment          = #c5cbd3
correct-subtle   = #bdadff
incorrect-subtle = #ff9980
subtle-separator = none
subtle-bg        = none
secondary        =
recursive-base   = #ffffff

[command-point]
reserved-word     = #d69fd6
subcommand        = #68c1ee
alias             = #8abbff
suffix-alias      = #8abbff
global-alias      = #8abbff
builtin           = #d69fd6
function          = #8abbff
command           = #8abbff
precommand        = #d69fd6
hashed-command    = #8abbff
single-sq-bracket = #fbd065
double-sq-bracket = #fbd065
double-paren      = #72ca9b

[paths]
path          = #bdadff
pathseparator = #bdadff
path-to-dir   = #bdadff
globbing      = #ff66a1
globbing-ext  = none

[brackets]
paired-bracket  = bold
bracket-level-1 = #fa999c
bracket-level-2 = #fbd065
bracket-level-3 = #68c1ee

[arguments]
single-hyphen-option   = #7ae1d8
double-hyphen-option   = #7ae1d8
back-quoted-argument   = #7ae1d8
single-quoted-argument = #72ca9b
double-quoted-argument = #72ca9b
dollar-quoted-argument = #72ca9b
optarg-string          = #72ca9b
optarg-number          = #fbb360

[in-string]
back-dollar-quoted-argument           = #fbb360
back-or-dollar-double-quoted-argument = #fbb360

[other]
variable             = #fbb360
assign               = none
assign-array-bracket = none
history-expansion    = none

[math]
mathvar = #ff66a1
mathnum = #fbb360
matherr = #fa999c,bold

[for-loop]
forvar  = #ffffff
fornum  = #fbb360
foroper = #8abbff
forsep  = #8abbff

[case]
case-input       = #fbb360
case-parentheses = #ffffff
case-condition   = #d69fd6
