# vim:ft=dosini
[base]
default          = #111418
unknown-token    = #cd4246,bold
commandseparator = #00a396
redirection      = #00a396
here-string-tri  = #404854
here-string-text = #404854
here-string-var  = #404854
exec-descriptor  = none
comment          = #5f6b7c
correct-subtle   = #7961db
incorrect-subtle = #d33d17
subtle-separator = none
subtle-bg        = none
secondary        =
recursive-base   = #111418

[command-point]
reserved-word     = #9d3f9d
subcommand        = #147eb3
alias             = #2d72d2
suffix-alias      = #2d72d2
global-alias      = #2d72d2
builtin           = #9d3f9d
function          = #2d72d2
command           = #2d72d2
precommand        = #9d3f9d
hashed-command    = #2d72d2
single-sq-bracket = #d1980b
double-sq-bracket = #d1980b
double-paren      = #238551

[paths]
path          = #7961db
pathseparator = #7961db
path-to-dir   = #7961db
globbing      = #db2c6f
globbing-ext  = none

[brackets]
paired-bracket  = bold
bracket-level-1 = #cd4246
bracket-level-2 = #d1980b
bracket-level-3 = #147eb3

[arguments]
single-hyphen-option   = #00a396
double-hyphen-option   = #00a396
back-quoted-argument   = #00a396
single-quoted-argument = #238551
double-quoted-argument = #238551
dollar-quoted-argument = #238551
optarg-string          = #238551
optarg-number          = #c87619

[in-string]
back-dollar-quoted-argument           = #c87619
back-or-dollar-double-quoted-argument = #c87619

[other]
variable             = #c87619
assign               = none
assign-array-bracket = none
history-expansion    = none

[math]
mathvar = #db2c6f
mathnum = #c87619
matherr = #cd4246,bold

[for-loop]
forvar  = #111418
fornum  = #c87619
foroper = #2d72d2
forsep  = #2d72d2

[case]
case-input       = #c87619
case-parentheses = #111418
case-condition   = #9d3f9d
