# vim:ft=kitty

foreground              #111418
background              #f6f7f9

selection_foreground    #111418
selection_background    #d3d8de

cursor                  #111418
cursor_text_color       #f6f7f9

url_color               #147eb3

inactive_border_color   #5f6b7c
active_border_color     #2d72d2
bell_border_color       #c87619

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #f6f7f9
active_tab_background   #2d72d2
inactive_tab_foreground #f6f7f9
inactive_tab_background #5f6b7c
tab_bar_background      #d3d8de

color0                  #f6f7f9
color8                  #5f6b7c

color1                  #cd4246
color9                  #d33d17

color2                  #238551
color10                 #29a634

color3                  #c87619
color11                 #946638

color4                  #2d72d2
color12                 #147eb3

color5                  #db2c6f
color13                 #9d3f9d

color6                  #147eb3
color14                 #00a396

color7                  #111418
color15                 #5f6b7c
