# vim:ft=kitty

foreground              #ffffff
background              #1c2127

selection_foreground    #ffffff
selection_background    #404854

cursor                  #ffffff
cursor_text_color       #1c2127

url_color               #68c1ee

inactive_border_color   #c5cbd3
active_border_color     #8abbff
bell_border_color       #fbb360

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #1c2127
active_tab_background   #8abbff
inactive_tab_foreground #1c2127
inactive_tab_background #c5cbd3
tab_bar_background      #404854

color0                  #1c2127
color8                  #c5cbd3

color1                  #fa999c
color9                  #ff9980

color2                  #72ca9b
color10                 #62d96b

color3                  #fbb360
color11                 #d0b090

color4                  #8abbff
color12                 #68c1ee

color5                  #ff66a1
color13                 #d69fd6

color6                  #68c1ee
color14                 #7ae1d8

color7                  #ffffff
color15                 #c5cbd3
