# vim:ft=kitty

foreground              #{{fg}}
background              #{{bg}}

selection_foreground    #{{fg}}
selection_background    #{{bgGray}}

cursor                  #{{fg}}
cursor_text_color       #{{bg}}

url_color               #{{cerulean}}

inactive_border_color   #{{gray}}
active_border_color     #{{blue}}
bell_border_color       #{{orange}}

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #{{bg}}
active_tab_background   #{{blue}}
inactive_tab_foreground #{{bg}}
inactive_tab_background #{{gray}}
tab_bar_background      #{{bgGray}}

color0                  #{{bg}}
color8                  #{{gray}}

color1                  #{{red}}
color9                  #{{vermilion}}

color2                  #{{green}}
color10                 #{{forest}}

color3                  #{{orange}}
color11                 #{{sepia}}

color4                  #{{blue}}
color12                 #{{cerulean}}

color5                  #{{rose}}
color13                 #{{violet}}

color6                  #{{cerulean}}
color14                 #{{turquoise}}

color7                  #{{fg}}
color15                 #{{gray}}
